# Generated by Django 3.1.1 on 2021-01-12 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_fileu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileu',
            name='user',
        ),
    ]
