# Generated by Django 3.1.1 on 2021-01-12 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_fileu_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
