# Generated by Django 3.1.1 on 2021-01-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210112_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='previews'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='files'),
        ),
    ]
